version: '3.8'

services:
  dashboard-geckodriver:
    container_name: 'dashboard-geckodriver'
    image: instrumentisto/geckodriver:117.0.1-driver0.33.0-debian

    command: --host=dashboard-geckodriver
    restart: on-failure
    networks:
      - dashboard-ntw
    deploy:
      resources:
        limits:
          memory: 250M
          cpus: '0.3'
        reservations:
          memory: 250M

  dashboard-api:
    container_name: 'dashboard-api'
    image: diogovalentte/personal-dashboard:1.0.0

    working_dir: /dashboard-api
    volumes:
      - .:/dashboard-api
    user: 0:0
    command: etc/docker/dashboard-api.sh
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/v1/health || exit 1"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 1m
    restart: on-failure
    depends_on:
      - dashboard-geckodriver
    networks:
      - dashboard-ntw
    deploy:
      resources:
        limits:
          memory: 250M
          cpus: '0.4'
        reservations:
          memory: 250M

  dashboard:
    container_name: 'dashboard'
    image: python:3.10.12

    working_dir: /dashboard
    volumes:
      - .:/dashboard
    ports:
      - 8501:8501
    command: etc/docker/dashboard.sh
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure
    depends_on:
      dashboard-api:
        condition: service_healthy
    networks:
      - dashboard-ntw
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: '0.3'
        reservations:
          memory: 200M

networks:
  dashboard-ntw:
    name: personal-dashboard
